version: "3"
services:
  api:
    build: ./api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - api_db
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://api_db:27017/api
  api_db:
    image: mongo:latest